pimcore_data_hub:
    configurations:
        travel:
            general:
                type: graphql
                path: null
                name: travel
                modificationDate: 1755351557
                createDate: 1755351557
            workspaces: {  }
            permissions:
                user: {  }
                role: {  }
